name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions: {}
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Compact Compiler
        uses: midnightntwrk/setup-compact-action@836895c8fffbbea6bd986af2b17e8941ff29d1f8
        with:
          compact-version: 0.31.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Compile and test contract
        working-directory: contracts
        run: npm run ci
      - name: api
        working-directory: api
        run: npm run ci
      - name: Compile cli
        working-directory: cli
        run: npm run ci
      - name: Compile ui
        working-directory: ui
        run: npm run ci
